### ISSUE TITLE
ライセンスに関する記述がない

### ISSUE THREAD

**Issue by kumagi** [wakayama-pref-org/list-of-public-facilities#4]
これらのデータをどのように利用して良いかを配布元が明示する必要があります。
それがない限り真っ当な組織はこれらのデータに触れる事ができません。
詳細についてはwikipediaの[オープンデータ](http://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%BC%E3%83%97%E3%83%B3%E3%83%87%E3%83%BC%E3%82%BF) のページが詳しいです。

更には「データを利用して生じた損害」について、通常はライセンス条項の中に免責事項が含まれるものですが、このリポジトリにはその旨すら明記されていません。
これは潜在的に訴訟リスクを抱えているという見方もできます。

適用するライセンスの前例としては例えばアメリカ政府のオープンデータの[ページ](https://github.com/GSA/data.gov/blob/master/LICENSE.md)にはWordpress周りがGPLで、プロジェクトへの貢献はすべてCC0(又の名をパブリックドメイン)である事を明示しています。

また、カナダ政府は [Open Government License](http://open.canada.ca/en/open-government-licence-canada) というものを適用しているようです。

これらを参考に、このリポジトリにもデータ公開者にとって最適と思われるライセンスを吟味した上でその内容を日本語と英語で記述した **LICENSE.md** ファイルを追加し、データのライセンス形態を明示して頂きたいです。

**Comment by miura1729** [comment]
:+1:
